In [438]:
#The machine settings are listed.

from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 4960728300452282736]

In [439]:
#Check the activated GPU device on remote machine

import tensorflow as tf
tf.test.gpu_device_name()

''

In [440]:
#Impoooooortam tot ce trebuie :)

In [441]:
import numpy as np
import pandas as pd
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import Input, Dense, Embedding, Conv2D, MaxPool2D, Conv1D, MaxPooling1D, GlobalMaxPooling1D
from tensorflow.python.keras.layers import Reshape, Flatten, Dropout, Concatenate
from tensorflow.python.keras.optimizers import RMSprop
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.optimizers import Adam
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
from tensorflow.python.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, f1_score, confusion_matrix
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix
import gensim, logging

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
import time

from gensim.models.word2vec import Word2Vec
from glob import glob

In [442]:
#Data load

In [443]:
tweets=[]
import csv
with open('test_dataset.csv', encoding="utf8") as csvfile:
    spamreader = csv.reader(csvfile)
    for row in spamreader:
        tweets.append(row);

In [444]:
len(tweets)

3044

In [445]:
tweets[1][1]

'Facebook Roundup: #LondonsSchoolSucks London_ Pages_ School_ Spam_ Foursquare @AmyBello @Sharmdja... http://bit.ly/p2yedk or  http://bit.ly/p2yXBn'

In [446]:
tweets_text_list=[]
tweets_label_list=[]
for row in tweets:
    tweets_text_list.append(row[1])
    tweets_label_list.append(row[8])

In [447]:
tweets_text_list
del tweets_text_list[0]

In [448]:
del tweets_label_list[0]
tweets_label_list

['0',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '0',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '0',
 '0',
 '1',
 '0',
 '1',
 '1',
 '0',
 '',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',

In [449]:
print("Tweets : ",len(tweets_label_list))
value1 = [i for i in tweets_label_list if i in '0']
value2 = [i for i in tweets_label_list if i in '1']
value3 = [i for i in tweets_label_list if i in '']
print("class 0: ",len(value1))
print("class 1: ",len(value2))
print("fara label: ", len(value3))

Tweets :  3043
class 0:  251
class 1:  2812
fara label:  20


In [450]:
aux_list=[]
aux_label_list=[]
unlabeled_tweets=[]
#Trebuie sa eliminaaam tweet urile fara label
for i in range(len(tweets_text_list)):
    if tweets_label_list[i]!='':
        aux_list.append(tweets_text_list[i])
        aux_label_list.append(tweets_label_list[i])
    else:
        unlabeled_tweets.append(tweets_text_list[i])

In [451]:
tweets_text_list=aux_list
tweets_label_list=aux_label_list
unlabeled_tweets

['Cleanup efforts in Clapham_ the people of London are quickly rebuilding and restoring lives. Such a great photo! http://fb.me/1amol0TJb',
 '#london #jobs Senior Health Economist - Pharma: Location: Bracknell BerkshireSalary: 50000-59000',
 'Freelance: Social Media Executive (Freelance - 8 Weeks) -  London: Social Media Executive (Freelance - 8 Weeks)',
 'Book a flight to London. ',
 '@cc_1224 I remember when you came to London_ I was close but in meetings. But you enjoyed our city and will again. :-)',
 'RT : Blazes_ looting in London riot #police #shooting #savePeople #spreadNews ',
 'Blazes_ looting in London riot #police #shooting #savePeople #spreadNews ',
 'London massive lootings explained as unrest caused by "social exclusion". Crime on a massive scale is still crime.  ',
 'London massive lootings explained as unrest caused by "social exclusion". Crime on a massive scale is still crime.  ',
 'Blazes_ looting in London riot #police #shooting #savePeople #spreadNews ',
 'Blazes_

In [452]:
print("Tweets : ",len(tweets_label_list))
value1 = [i for i in tweets_label_list if i in '0']
value2 = [i for i in tweets_label_list if i in '1']
value3 = [i for i in tweets_label_list if i in '']
print("class 0: ",len(value1))
print("class 1: ",len(value2))
print("fara label: ", len(value3))

Tweets :  3023
class 0:  231
class 1:  2792
fara label:  0


In [453]:
#Preprocesaaaaare

In [454]:
from nltk.stem import PorterStemmer 
from nltk.tokenize import word_tokenize 
import re


def splitIntoStem(message):

    
    return [removeNumeric(stripEmoji(singleCharacterRemove(removePunctuation
                                                           (removeHyperlinks
                                                            (removeHashtags
                                                             (removeUsernames
                                                              (stemWord(word)))))))) for word in message.split()]
def stemWord(tweet):

    ps = PorterStemmer()                       
    return ps.stem(tweet).lower()
    

#Remove usernames
def removeUsernames(tweet):
    return re.sub('@[^\s]+', '', tweet)


#Remove hashtag
def removeHashtags(tweet):
    return re.sub(r'#[^\s]+', '', tweet)

#Remove link
def removeHyperlinks(tweet):
    return re.sub('((www\.[^\s]+)|(https?://[^\s]+))', '', tweet)

#Remove numeric character
def removeNumeric(value):
    blist2 = [item for item in value if not item.isdigit()]
    blist3 = "".join(blist2)
    return blist3

#Remove punctuation
def removePunctuation(tweet):

    return re.sub(r'[^\w\s]','',tweet)

#Remove single character
def singleCharacterRemove(tweet):
    tweet=tweet.replace('_', '')
    return re.sub(r'(?:^| )\w(?:$| \ )', ' ', tweet)

#Remove emoji
def stripEmoji(text):

    RE_EMOJI = re.compile('[\U00010000-\U0010ffff]', flags=re.UNICODE)
    return RE_EMOJI.sub(r'', text)

In [455]:
filtered_tweets=[]
unlabeled_filtered_tweets=[]
for i,k in enumerate(tweets_text_list):
    filtered_tweets.append(" ".join(splitIntoStem(k)).split())
for i,k in enumerate(unlabeled_tweets):
    unlabeled_filtered_tweets.append(" ".join(splitIntoStem(k)).split())

In [456]:
filtered_tweets[0]

['facebook', 'roundup', 'london', 'pages', 'school', 'spam', 'foursquar', 'or']

In [457]:
tweets_text_list[0]

'Facebook Roundup: #LondonsSchoolSucks London_ Pages_ School_ Spam_ Foursquare @AmyBello @Sharmdja... http://bit.ly/p2yedk or  http://bit.ly/p2yXBn'

In [458]:
unlabeled_filtered_tweets[0]

['cleanup',
 'effort',
 'in',
 'clapham',
 'the',
 'peopl',
 'of',
 'london',
 'are',
 'quickli',
 'rebuild',
 'and',
 'restor',
 'lives',
 'such',
 'great',
 'photo']

In [459]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Roxanica\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [460]:
#Eliminaaam stop words

In [461]:
from nltk.corpus import stopwords


def removeStopWords(tweet_list):
    
    filtered_stopwords = []
    filtered_stopwords_list = []
    
    stop_words = stopwords.words('english')

    print("stop_words : ",stop_words)
    
    for i in filtered_tweets:
        filtered_sentence = [w for w in i if not w in stop_words]
        filtered_stopwords_list.append(filtered_sentence)                         #return list value
        filtered_stopwords.append(" ".join(filtered_sentence))                    #return string value
    
    return filtered_stopwords,filtered_stopwords_list                                      


filtered_tweets, filtered_stopwords_list = removeStopWords(filtered_tweets)

stop_words :  ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', '

In [462]:
filtered_tweets[0]

'facebook roundup london pages school spam foursquar'

In [463]:
unlabeled_filtered_tweets[0]

['cleanup',
 'effort',
 'in',
 'clapham',
 'the',
 'peopl',
 'of',
 'london',
 'are',
 'quickli',
 'rebuild',
 'and',
 'restor',
 'lives',
 'such',
 'great',
 'photo']

In [464]:
from nltk.corpus import stopwords


def removeStopWords_u(tweet_list):
    
    filtered_stopwords_u = []
    filtered_stopwords_list_u = []
    
    stop_words = stopwords.words('english')

    print("stop_words : ",stop_words)
    
    for i in unlabeled_filtered_tweets:
        filtered_sentence = [w for w in i if not w in stop_words]
        filtered_stopwords_list_u.append(filtered_sentence)                         #return list value
        filtered_stopwords_u.append(" ".join(filtered_sentence))                    #return string value
    
    return filtered_stopwords_u,filtered_stopwords_list_u                                      


filtered_unlabeled_tweets, filtered_stopwords_list = removeStopWords_u(unlabeled_filtered_tweets)


stop_words :  ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', '

In [465]:
filtered_unlabeled_tweets.remove('')
filtered_unlabeled_tweets

['cleanup effort clapham peopl london quickli rebuild restor lives great photo',
 'senior health economist pharma location bracknel berkshiresalary',
 'freelance social media execut freelanc weeks london social media execut freelanc weeks',
 'book flight london',
 'rememb came london wa close meetings enjoy citi',
 'rt blazes loot london riot',
 'blazes loot london riot',
 'london massiv loot explain unrest caus social exclusion crime massiv scale still crime',
 'london massiv loot explain unrest caus social exclusion crime massiv scale still crime',
 'blazes loot london riot',
 'blazes loot london riot',
 'london riots bbc never replay send',
 'riots bbc never replay send',
 'london citi soccer',
 'emi bid rang bln blnft london aug reuters bid emi lndoneul suggest',
 'disturb london protest',
 '',
 'triathlonphotos prerac activ london',
 'triathlonphotos prerac activ london']

In [466]:
tweets_text_list[0]

'Facebook Roundup: #LondonsSchoolSucks London_ Pages_ School_ Spam_ Foursquare @AmyBello @Sharmdja... http://bit.ly/p2yedk or  http://bit.ly/p2yXBn'

In [467]:
df = pd.DataFrame({"tweet":filtered_tweets,"label":tweets_label_list})
df.head()

tweet label
0  facebook roundup london pages school spam four...     0
1       facebook roundup pages school spam foursquar     0
2  rt new guidelin product brand london olymp bik...     1
3  rt new guidelin product brand london olymp bik...     1
4   london brand new appl macbook pro london price â     1

In [468]:
df.iloc[0]

tweet    facebook roundup london pages school spam four...
label                                                    0
Name: 0, dtype: object

In [469]:
target = df['label'].values.tolist()
data = df['tweet'].values.tolist()

In [470]:
x_train, x_test, y_train, y_test = \
    train_test_split(data, target, test_size=0.2)

In [471]:
print("x_train :",len(x_train))
print("x_test :",len(x_test))

x_train : 2418
x_test : 605


In [472]:
x_train[800]

'tfl transport london mayor transport organisation much loved londoners'

In [473]:
tokenizer = Tokenizer()             #Tokenizer(num_words=5000) => 5000 words of the highest frequency
tokenizer.fit_on_texts(data)
tokenizer 

In [474]:
list(tokenizer.word_index)[0:10]

['london', 'checkzz', 'rt', 'riot', 'link', 'bio', 'go', 'im', 'thi', 'polic']

In [475]:
print("len(tokenizer) :",len(list(tokenizer.word_index)))

len(tokenizer) : 6440


In [476]:
#Training set token with text_to_sequences.

x_train_tokens = tokenizer.texts_to_sequences(x_train)

In [477]:
x_train[800]

'tfl transport london mayor transport organisation much loved londoners'

In [478]:
print(x_train_tokens[800])

[4673, 239, 1, 397, 239, 4674, 83, 4675, 4676]


In [479]:
x_test_tokens = tokenizer.texts_to_sequences(x_test)

In [480]:
num_tokens = [len(tokens) for tokens in x_train_tokens + x_test_tokens]
num_tokens = np.array(num_tokens)

In [481]:
num_tokens[800]

9

In [482]:
np.max(num_tokens)

138

In [483]:
np.argmax(num_tokens)

1146

In [484]:
x_train[np.argmax(num_tokens)]

'perbuatan biadab disela kerusuhan london bio link indonesia inforoot soccer leagu cup game cancel due london riots due larg number riot occur bio link mullins inforoot riot london whaaat someon care explain inforoot al je mn tele wilt moet je voor donderdag komen halen want donderdag ga ik miss naar londonvolg inforoot need come londonmichael day inforoot got work tomoro hav sum friend comin london stay us quit excit altho wont twitter muchlillie inforoot oh londonudahlah jgn rusuhtar premier leagu keganggugw ga ada tontonan bola soalnyakompetisi pssi ramean kepengurusan bukan liganyarully inforoot hey big support ministri londonjust show love aw wow thank muchth wall group inforoot rememb movi ghosts went music night londonlov itim theatr junkielov dem ting deh inforoot stay safe ur london wednesday ikk worri lad days xxxbonnie inforoot wait olymp come thi london imagin lool'

In [485]:
max_tokens = np.mean(num_tokens) + 2 * np.std(num_tokens)
max_tokens = int(max_tokens)
max_tokens

18

In [486]:
#How many of the eighteen length tweets are included?

np.sum(num_tokens < max_tokens) / len(num_tokens)

0.9824677472709229

In [487]:
x_train_pad = pad_sequences(x_train_tokens, maxlen=max_tokens)

In [488]:
#Zero is added before the values given in the padding operation.

print("x_train_tokens :",x_train_tokens[0])
print("x_train_pad :",x_train_pad[0])

x_train_tokens : [127, 60, 129, 1012, 959, 1012, 4284, 127, 60, 4285, 2]
x_train_pad : [   0    0    0    0    0    0    0  127   60  129 1012  959 1012 4284
  127   60 4285    2]


In [489]:
x_test_pad = pad_sequences(x_test_tokens, maxlen=max_tokens)

In [490]:
print("x_test_tokens :",x_test_tokens[0])
print("x_train_pad :",x_test_pad[0])

x_test_tokens : [105, 2518, 6270, 1, 9, 92, 168, 33, 2521, 1239]
x_train_pad : [   0    0    0    0    0    0    0    0  105 2518 6270    1    9   92
  168   33 2521 1239]


In [491]:
print("x_train_pad.shape :",x_train_pad.shape)
print("x_train_pad.shape :",x_test_pad.shape)

x_train_pad.shape : (2418, 18)
x_train_pad.shape : (605, 18)


In [492]:
idx = tokenizer.word_index
inverse_map = dict(zip(idx.values(), idx.keys()))

In [493]:
def tokens_to_string(tokens):
    words = [inverse_map[token] for token in tokens if token!=0]
    text = ' '.join(words)
    return text

In [494]:
x_train[800]

'tfl transport london mayor transport organisation much loved londoners'

In [495]:
print(x_train_tokens[800])

[4673, 239, 1, 397, 239, 4674, 83, 4675, 4676]


In [496]:
tokens_to_string(x_train_tokens[800])

'tfl transport london mayor transport organisation much loved londoners'

In [497]:
#Embedding operations

In [541]:
filtered_stopwords_list[0]

['cleanup',
 'effort',
 'clapham',
 'peopl',
 'london',
 'quickli',
 'rebuild',
 'restor',
 'lives',
 'great',
 'photo']

In [543]:
#Save word2vec format (not binary)

model = Word2Vec(filtered_stopwords_list)
print(model)
model_save_location = "tweets_notbinary"
model.wv.save_word2vec_format(model_save_location)


2020-04-06 21:41:03,804 : INFO : collecting all words and their counts
2020-04-06 21:41:03,805 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2020-04-06 21:41:03,806 : INFO : collected 65 word types from a corpus of 121 raw words and 20 sentences
2020-04-06 21:41:03,807 : INFO : Loading a fresh vocabulary
2020-04-06 21:41:03,808 : INFO : effective_min_count=5 retains 2 unique words (3% of original 65, drops 63)
2020-04-06 21:41:03,809 : INFO : effective_min_count=5 leaves 22 word corpus (18% of original 121, drops 99)
2020-04-06 21:41:03,810 : INFO : deleting the raw counts dictionary of 65 items
2020-04-06 21:41:03,810 : INFO : sample=0.001 downsamples 2 most-common words
2020-04-06 21:41:03,811 : INFO : downsampling leaves estimated 1 word corpus (4.5% of prior 22)
2020-04-06 21:41:03,812 : INFO : estimated required memory for 2 words and 100 dimensions: 2600 bytes
2020-04-06 21:41:03,812 : INFO : resetting layer weights
2020-04-06 21:41:03,814 : INFO : tr

Word2Vec(vocab=2, size=100, alpha=0.025)


In [504]:
embedding_size = 100 

In [539]:
#Word2vec load(2.option) example

word2vec = {}
with open('tweets_notbinary', encoding='UTF-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        print(word)
        vec = np.asarray(values[1:], dtype='float32')
        word2vec[word] = vec

2
london
loot


In [506]:
print("x_test[1] :",x_test[1])
print("x_test_pad[1] :",x_test_pad[1])

x_test[1] : work top london model agenc call looker
x_test_pad[1] : [   0    0    0    0    0    0    0    0    0    0    0   89  151    1
 1583  668  133 6368]


In [507]:
num_words = len(list(tokenizer.word_index))
num_words

6440

In [508]:
embedding_matrix = np.random.uniform(-1, 0, (num_words+1, embedding_size))
for word, i in tokenizer.word_index.items():
    if i < num_words:
        embedding_vector = word2vec.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [509]:
embedding_matrix.shape

(6441, 100)

In [538]:
word2vec

{'2': array([100.], dtype=float32),
 'london': array([ 3.8424553e-03, -2.2838530e-03, -3.0143522e-03,  2.4347934e-03,
        -4.1387160e-03, -2.8542376e-03,  2.7846158e-03, -3.8115941e-03,
        -4.6504592e-03, -2.7189122e-03, -2.0575700e-03, -4.7897738e-03,
         1.4519703e-03,  5.8968546e-04,  4.1407091e-03,  1.6365096e-03,
        -1.0659023e-03, -2.0151774e-03,  8.7965120e-05, -4.5869900e-03,
         2.6919073e-03,  3.3096762e-03, -3.0899076e-03, -1.9432980e-03,
        -2.9042671e-03, -1.6305504e-03, -3.2770068e-03,  4.2736498e-03,
         3.1735075e-03,  8.3671766e-04,  1.4009308e-03, -8.0937799e-04,
        -4.5718085e-03, -4.6393634e-03,  1.9156239e-04, -3.2500345e-03,
         3.0848137e-03,  2.4407043e-03,  1.6724347e-05, -1.1905867e-03,
        -4.0086107e-03, -2.1275415e-03,  1.5739833e-03, -3.6463456e-03,
         4.4798041e-03, -3.4223683e-03,  5.3572573e-04, -3.9879109e-05,
         3.6948377e-03, -2.0562937e-03,  1.8272239e-04,  1.7419485e-03,
        -1.0752700

In [533]:
embedding_matrix[0]

array([-0.76928148, -0.64693835, -0.7298864 , -0.99696975, -0.78386647,
       -0.92315654, -0.1016227 , -0.3894247 , -0.92895017, -0.20991172,
       -0.07065759, -0.0043379 , -0.13894763, -0.50358192, -0.84148005,
       -0.88591407, -0.31443385, -0.81890978, -0.59805769, -0.53464038,
       -0.00650707, -0.65098198, -0.24260558, -0.76650254, -0.42686459,
       -0.50125806, -0.25816101, -0.92453469, -0.71996442, -0.70303242,
       -0.80968557, -0.33692404, -0.82924931, -0.98574054, -0.3560607 ,
       -0.33291955, -0.09805998, -0.98494714, -0.69112342, -0.35247695,
       -0.7630395 , -0.14066357, -0.90932862, -0.24340056, -0.99005106,
       -0.74964489, -0.73355949, -0.74776258, -0.91256499, -0.65965357,
       -0.51164343, -0.79927932, -0.91905301, -0.60846795, -0.4467129 ,
       -0.95687322, -0.9218611 , -0.35818776, -0.98712193, -0.31314223,
       -0.00849346, -0.950322  , -0.58228955, -0.72777067, -0.8651078 ,
       -0.4198136 , -0.53959316, -0.44939766, -0.94224139, -0.95

In [511]:
sequence_length = max_tokens
vocabulary_size = num_words
embedding_dim = embedding_size
filter_sizes = [3,4,5]
num_filters = 512
drop = 0.5
epochs = 5
batch_size = 30

In [512]:
y_train2 = []
y_test2 = []
for i in y_train:
  y_train2.append(int(i))
for i in y_test:
  y_test2.append(int(i))

In [513]:
tf.compat.v1.disable_eager_execution()

In [514]:
#CNN architecture

num_classes = 2

#Training params
batch_size = 256 
num_epochs = 5

#Model parameters
num_filters = 64  
embed_dim = embedding_size
weight_decay = 1e-5

print("training CNN ...")
model = Sequential()

#Model add word2vec embedding

model.add(Embedding(input_dim=num_words+1,
                    output_dim=embedding_size,
                    weights= [embedding_matrix],
                    input_length=max_tokens,        
                    trainable=True,              #the layer is trained
                    name='embedding_layer'))
model.add(Conv1D(num_filters, 7, activation='relu', padding='same'))
model.add(MaxPooling1D(2))
model.add(Conv1D(num_filters, 7, activation='relu', padding='same'))
model.add(GlobalMaxPooling1D())
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Dense(num_classes, activation='softmax'))  #multi-label (k-hot encoding)

adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(loss='sparse_categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
model.summary()



#define callbacks
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0.01, patience=4, verbose=1)
callbacks_list = [early_stopping]


hist = model.fit(x_train_pad, y_train2, batch_size=batch_size, epochs=num_epochs, callbacks=callbacks_list, validation_split=0.1, shuffle=True, verbose=2)


training CNN ...
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_layer (Embedding)  (None, 18, 100)           644100    
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 18, 64)            44864     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 9, 64)             0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 9, 64)             28736     
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 64)                0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 3

In [515]:
model.fit(x_train_pad, y_train2, batch_size=batch_size, epochs=num_epochs, callbacks=callbacks_list, validation_split=0.1, shuffle=True, verbose=2)

Train on 2176 samples, validate on 242 samples
Epoch 1/5
2176/2176 - 0s - loss: 0.2581 - accuracy: 0.9265 - val_loss: 0.2812 - val_accuracy: 0.9215
Epoch 2/5
2176/2176 - 0s - loss: 0.2587 - accuracy: 0.9265 - val_loss: 0.2790 - val_accuracy: 0.9215
Epoch 3/5
2176/2176 - 0s - loss: 0.2489 - accuracy: 0.9265 - val_loss: 0.2701 - val_accuracy: 0.9215
Epoch 4/5
2176/2176 - 0s - loss: 0.2503 - accuracy: 0.9265 - val_loss: 0.2789 - val_accuracy: 0.9215
Epoch 5/5
2176/2176 - 0s - loss: 0.2337 - accuracy: 0.9265 - val_loss: 0.2696 - val_accuracy: 0.9215


In [516]:
model.save('model1.h5')

In [517]:
#Incercaaaaam sa evaluuuaaaam modelul

In [518]:
x_test_pad

array([[   0,    0,    0, ...,   33, 2521, 1239],
       [   0,    0,    0, ...,  668,  133, 6368],
       [   0,    0,    0, ...,  447,   14,  117],
       ...,
       [   0,    0,    0, ...,  271,    1, 2353],
       [   0,    0,    0, ...,    6,    5,   29],
       [   0,    0,    0, ..., 2443,  281,  206]])

In [519]:
num_classes = 2

#Training params
batch_size = 256 
num_epochs = 5

#Model parameters
num_filters = 64  # görüntünün boyutu mesela 512*512
embed_dim = embedding_size
weight_decay = 1e-5

In [520]:
model.evaluate(x_test_pad, y_test2, batch_size, verbose=1, sample_weight=None, steps=None, callbacks=callbacks_list, max_queue_size=10, workers=1, use_multiprocessing=False)

605/605 [==============================] - 0s 39us/sample - loss: 0.2613 - accuracy: 0.9140


[0.2612976095154266, 0.91404957]

In [521]:
result=model.predict(x_train_pad, batch_size, verbose=0, steps=None, callbacks=callbacks_list, max_queue_size=10, workers=1, use_multiprocessing=False)

In [530]:
result[1]

array([0.05504617, 0.9449538 ], dtype=float32)

In [523]:
y_train2[1]

1

In [524]:
###Exportare rezultat ca csv
with open('rezultaaaat.csv', mode='w') as cv:
    scris = csv.writer(cv)
    for index in range(len(result)):
        scris.writerow([result[index][0], result[index][1] , y_train[index]])

In [525]:
x_train_pad[0]


array([   0,    0,    0,    0,    0,    0,    0,  127,   60,  129, 1012,
        959, 1012, 4284,  127,   60, 4285,    2])

In [526]:
x_unlabeled_tokens = tokenizer.texts_to_sequences(filtered_unlabeled_tweets)
x_unlabeled_pad= pad_sequences(x_unlabeled_tokens, maxlen=max_tokens)

In [527]:
x_unlabeled_pad

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0, 1266,   24,    1,  159,  180],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,   61, 1138,  895],
       [   0,    0,    0,    0,    0,    0,    0,    0, 3380,  127,   60,
        1460, 1343,    1,  127,   60, 1460, 1343],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,  410,  392,    1],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         581,  388,    1,   17,  924,  361,   57],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    3, 1232,   82,    1,    4],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0, 1232,   82,    1,    4],
       [   0,    0,    0,    0,    0,    0,    1, 1372,   82, 1623,  757,
         209,  127, 5761, 1372, 2039,   78, 5761],


In [528]:
result=model.predict(x_train_pad, batch_size, verbose=0, steps=None, callbacks=callbacks_list, max_queue_size=10, workers=1, use_multiprocessing=False)

In [529]:
result

array([[0.04235659, 0.95764345],
       [0.05504617, 0.9449538 ],
       [0.09127739, 0.9087226 ],
       ...,
       [0.10588056, 0.89411944],
       [0.06583234, 0.9341677 ],
       [0.04062131, 0.9593787 ]], dtype=float32)